/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package entity;

import jakarta.persistence.Basic;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.NamedQueries;
import jakarta.persistence.NamedQuery;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import jakarta.xml.bind.annotation.XmlRootElement;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * @author MINH_QUAN
 */
@Entity
@Table(name = "reorder_requests", catalog = "semiconductor_inventory_db", schema = "dbo")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "ReorderRequests.findAll", query = "SELECT r FROM ReorderRequests r"),
    @NamedQuery(name = "ReorderRequests.findByRequestId", query = "SELECT r FROM ReorderRequests r WHERE r.requestId = :requestId"),
    @NamedQuery(name = "ReorderRequests.findByRequestedQuantity", query = "SELECT r FROM ReorderRequests r WHERE r.requestedQuantity = :requestedQuantity"),
    @NamedQuery(name = "ReorderRequests.findByEstimatedCost", query = "SELECT r FROM ReorderRequests r WHERE r.estimatedCost = :estimatedCost"),
    @NamedQuery(name = "ReorderRequests.findByPriority", query = "SELECT r FROM ReorderRequests r WHERE r.priority = :priority"),
    @NamedQuery(name = "ReorderRequests.findByStatus", query = "SELECT r FROM ReorderRequests r WHERE r.status = :status"),
    @NamedQuery(name = "ReorderRequests.findByReason", query = "SELECT r FROM ReorderRequests r WHERE r.reason = :reason"),
    @NamedQuery(name = "ReorderRequests.findByAutoGenerated", query = "SELECT r FROM ReorderRequests r WHERE r.autoGenerated = :autoGenerated"),
    @NamedQuery(name = "ReorderRequests.findByRequestDate", query = "SELECT r FROM ReorderRequests r WHERE r.requestDate = :requestDate"),
    @NamedQuery(name = "ReorderRequests.findByApprovedAt", query = "SELECT r FROM ReorderRequests r WHERE r.approvedAt = :approvedAt"),
    @NamedQuery(name = "ReorderRequests.findByOrderDate", query = "SELECT r FROM ReorderRequests r WHERE r.orderDate = :orderDate"),
    @NamedQuery(name = "ReorderRequests.findByExpectedDelivery", query = "SELECT r FROM ReorderRequests r WHERE r.expectedDelivery = :expectedDelivery"),
    @NamedQuery(name = "ReorderRequests.findByNotes", query = "SELECT r FROM ReorderRequests r WHERE r.notes = :notes")})
public class ReorderRequests implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "request_id", nullable = false)
    private Integer requestId;
    @Basic(optional = false)
    @NotNull
    @Column(name = "requested_quantity", nullable = false)
    private int requestedQuantity;
    // @Max(value=?)  @Min(value=?)//if you know range of your decimal fields consider using these annotations to enforce field validation
    @Column(name = "estimated_cost", precision = 12, scale = 2)
    private BigDecimal estimatedCost;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 20)
    @Column(name = "priority", nullable = false, length = 20)
    private String priority;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 20)
    @Column(name = "status", nullable = false, length = 20)
    private String status;
    @Size(max = 2147483647)
    @Column(name = "reason", length = 2147483647)
    private String reason;
    @Basic(optional = false)
    @NotNull
    @Column(name = "auto_generated", nullable = false)
    private boolean autoGenerated;
    @Column(name = "request_date")
    @Temporal(TemporalType.TIMESTAMP)
    private Date requestDate;
    @Column(name = "approved_at")
    @Temporal(TemporalType.TIMESTAMP)
    private Date approvedAt;
    @Column(name = "order_date")
    @Temporal(TemporalType.TIMESTAMP)
    private Date orderDate;
    @Column(name = "expected_delivery")
    @Temporal(TemporalType.DATE)
    private Date expectedDelivery;
    @Size(max = 2147483647)
    @Column(name = "notes", length = 2147483647)
    private String notes;
    @JoinColumn(name = "component_id", referencedColumnName = "component_id", nullable = false)
    @ManyToOne(optional = false)
    private Components componentId;
    @JoinColumn(name = "supplier_id", referencedColumnName = "supplier_id")
    @ManyToOne
    private Suppliers supplierId;
    @JoinColumn(name = "approved_by", referencedColumnName = "user_id")
    @ManyToOne
    private Users approvedBy;

    public ReorderRequests() {
    }

    public ReorderRequests(Integer requestId) {
        this.requestId = requestId;
    }

    public ReorderRequests(Integer requestId, int requestedQuantity, String priority, String status, boolean autoGenerated) {
        this.requestId = requestId;
        this.requestedQuantity = requestedQuantity;
        this.priority = priority;
        this.status = status;
        this.autoGenerated = autoGenerated;
    }

    public Integer getRequestId() {
        return requestId;
    }

    public void setRequestId(Integer requestId) {
        this.requestId = requestId;
    }

    public int getRequestedQuantity() {
        return requestedQuantity;
    }

    public void setRequestedQuantity(int requestedQuantity) {
        this.requestedQuantity = requestedQuantity;
    }

    public BigDecimal getEstimatedCost() {
        return estimatedCost;
    }

    public void setEstimatedCost(BigDecimal estimatedCost) {
        this.estimatedCost = estimatedCost;
    }

    public String getPriority() {
        return priority;
    }

    public void setPriority(String priority) {
        this.priority = priority;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public boolean getAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public Date getRequestDate() {
        return requestDate;
    }

    public void setRequestDate(Date requestDate) {
        this.requestDate = requestDate;
    }

    public Date getApprovedAt() {
        return approvedAt;
    }

    public void setApprovedAt(Date approvedAt) {
        this.approvedAt = approvedAt;
    }

    public Date getOrderDate() {
        return orderDate;
    }

    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    public Date getExpectedDelivery() {
        return expectedDelivery;
    }

    public void setExpectedDelivery(Date expectedDelivery) {
        this.expectedDelivery = expectedDelivery;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public Components getComponentId() {
        return componentId;
    }

    public void setComponentId(Components componentId) {
        this.componentId = componentId;
    }

    public Suppliers getSupplierId() {
        return supplierId;
    }

    public void setSupplierId(Suppliers supplierId) {
        this.supplierId = supplierId;
    }

    public Users getApprovedBy() {
        return approvedBy;
    }

    public void setApprovedBy(Users approvedBy) {
        this.approvedBy = approvedBy;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (requestId != null ? requestId.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof ReorderRequests)) {
            return false;
        }
        ReorderRequests other = (ReorderRequests) object;
        if ((this.requestId == null && other.requestId != null) || (this.requestId != null && !this.requestId.equals(other.requestId))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "entity.ReorderRequests[ requestId=" + requestId + " ]";
    }
    
}
